site_name: Gluu Docs
site_description: Documenation for the Gluu Server
site_favicon: '/img/gluu_favicon.ico'
copyright: Copyright &copy; 2016, Gluu, Inc.
docs_dir: source
repo_url: https://github.com/GluuFederation/docs
theme_dir: theme
extra:
    version: '2.4.4'
    logo: 'gluu.jpg'
markdown_extensions:
- admonition
- toc:
     permalink: '#'
pages:
- Home: 'index.md'
- Installation Guide:
    - Single Setup:
        - 'Preparing VM': 'installation-guide/index.md'
        - 'Install Gluu Server': 'installation-guide/install.md'
        - 'Setup Script Options': 'installation-guide/setup_py.md'
    - Cluster Setup:
        - 'Cluster Deployment Guide': 'cluster/index.md'
    - Upgrade Gluu Server:
        - 'Upgrade Guide' : 'upgrade/index.md'
    - Patch Gluu Server:
        - 'Update Gluu CE' : 'update/index.md'
- Administration Interface:
        - 'Introduction to oxTrust': 'oxtrust/index.md'
- Administration Guide:
        - 'Introduction' : 'admin-guide/index.md'
   - Authentication Protocols:
        - 'SAML': 'admin-guide/authentication-protocol-saml.md' 
        - 'Test SAML': 'admin-guide/authentication-protocol-saml-test.md'
        - 'OpenID Connect': 'admin-guide/authentication-protocol-openid.md'
        - 'Test OpenID': 'admin-guide/authentication-protocol-openid-test.md'
        - 'UMA': 'admin-guide/uma.md'
        - 'SCIM': 'admin-guide/scim.md'
        - 'Test SCIM' : 'admin-guide/scim-test.md'
        - 'Log Management' : 'admin-guide/logs.md'
   - Authentication Management:
    - '11. Introduction' : 'admin-guide/auth-management.md'


 - Reference Guide:
    - 1. 'Introduction': 'reference-guide/index.md'
    - 2. 'oxTrust JSON Config' : 'reference-guide/oxtrust-json.md'
    - 3. 'oxAuth JSON Config' : 'reference-guide/oxauth-json.md'
    - 4. 'Logs' : 'reference-guide/logs.md'
    - 5. 'Logout' : 'reference-guide/Logout.md'
    - 6. 'LDAP Schema' : 'reference-guide/ldapschema.md'
    - 7. 'LDAP' : 'reference-guide/ldap.md'
    - 8. 'Schema' : 'reference-guide/schema.md'
    - 9. 'Certificates' : 'reference-guide/certs.md'
    - 10. 'Configuration' : 
 	 
